config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "meetings#index"
  resources :meetings
end

app/models/meeting.rb
class Meeting
  include Mongoid::Document
  include Mongoid::Timestamps
  field :home_team_name, type: String
  field :away_team_name, type: String
  field :date, type: Date
  field :gate, type: String

  validates :date, :home_team_name, :away_team_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[show edit update destroy]
  def index
    @meetings = Meeting.all.order(date: :desc)
  end

  def new
    @meeting = Meeting.new
  end

  def edit
  end

  def create
    @meeting = Meeting.new(meeting_params)
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meetings_path notice: "Meeting was successfully created" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meetings_path, notice: "Meeting was successfully updated" }
      else
        format.html { render :edit }
      end
    end
  end
  def show
  end

  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully removed" }
    end
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end
  def meeting_params
    params.expect(meeting: [ :date, :home_team_name, :away_team_name, :gate ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Speedway Mb25" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbo-refresh-method" content="morph">

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>
  <div class="container-fluid">
    <%= yield %>
  </div>

  </body>
</html>

app/views/meetings/_form.html.erb
<%= simple_form_for @meeting do |f| %>
  <%= f.input :date, as: :string, placeholder: "#{Date.today}" %>
  <%= f.input :home_team_name, collection: @team_names %>
  <%= f.input :away_team_name, collection: @team_names %>
  <%= f.input :gate, collection: ["1 and 3", "2 and 4"] %>
  <div class="row">
    <div class="col-md-12">
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-fill bd-highlight">
          <%= f.submit data: {turbo_frame: "_top"}, class: "btn btn-sm btn-outline-success" %>
        </div>
        <div class="p-2 flex-fill bd-highlight">
          <%= link_to "Cancel", meetings_path, class: "btn btn-sm btn-outline-info" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h3>Edit Meeting</h3>

<%= turbo_frame_tag "edit_meeting" do %>
  <%= render 'form', meeting: @meeting %>
<% end %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row ">
  <div class="col-md-12">
    <div class="page-header"><h3>Meetings</h3></div>
  </div>
</div>

<div class="row ">
  <%= turbo_frame_tag "add_new_meeting" do %>
    <div class="col-md-12">
      <%= button_to "Add meetings", new_meeting_path, method: :get, class: "btn btn-small btn-outline-dark" %>
    </div>
  <% end %>
</div>

<% @meetings.each do |meeting| %>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <%= button_to meeting.date.strftime("%a %b %d"), meeting, method: :get, class: "btn btn-info btn-block" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-fill bd-highlight"><%= meeting.home_team_name %></div>
        <div class="p-2 flex-fill bd-highlight"><%= meeting.away_team_name %></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-fill bd-highlight">
          <%= turbo_frame_tag "edit_meeting" do %>
            <%= button_to 'Edit', edit_meeting_path(meeting), class: 'btn btn-sm btn-outline-secondary', method: :get %>
          <% end %>
        </div>
        <div class="p-2 flex-fill bd-highlight">
          <%= button_to 'Delete', meeting, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/meetings/new.html.erb
<h3>New Meeting</h3>

<%= turbo_frame_tag "add_new_meeting" do %>
  <%= render 'form', meeting: @meeting %>
<% end %>